### PR TITLE
fix: prevent empty class

### PR DESCRIPTION
**Pull request by charlierudolph**
@alexdavid

I am getting a lot of elements with an empty class attribute. 
To keep a cleaner DOM, I'd like `opts.className` to only be set when needed.

### CODE REVIEW

**Review by alexdavid — APPROVED** [review]
Awesome

**Comment by charlierudolph** [comment]
@alexdavid I don't have write access to this repo, so I can't merge it. This is really low priority so it can wait until you get back.

**Comment by alexdavid** [comment]
You should have write access now. Can you ship and `npm version patch`?

**Comment by charlierudolph** [comment]
1.0.2 released. Thanks @alexdavid

**Pull request merged**
